id: IBBB9629B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T05:10:57+00:00'
last_modified: '2022-06-07T20:23:08.570426+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18688
  title: མེང་ཙི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    ACC1:
      image_group_id: I8LS18690
      title: ''
      total_pages: 545
      order: 1
      base_file: ACC1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
