id: P003315
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18688
  title: མེང་ཙི།
  author: ''
  volumes:
    f3d86653a5834fa5a93b642136213853:
      image_group_id: I8LS18690
      title: ''
      volume_number: 1
      total_pages: 545
      base_file: v001.txt
